name: build and test

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  ubuntu-20-04:
    runs-on: ubuntu-20.04
    name: ubuntu-20.04 (mruby-${{matrix.TARGET_MRUBY}})
    strategy:
      matrix:
        TARGET_MRUBY:
        - master
        - 3.1.0
        - 3.0.0
        - 2.1.2
        - 2.1.1
        - 2.1.0
        - 2.0.1
        - 2.0.0
        - 1.4.1
        - 1.4.0
        - 1.3.0
        - 1.2.0
    env:
      MRUBY_URL: "https://github.com/mruby/mruby/archive/${{matrix.TARGET_MRUBY}}.tar.gz"
      MRUBY_DIR: "mruby-${{matrix.TARGET_MRUBY}}"
      MRUBY_CONFIG: ../test_config.rb
      CC: clang
    steps:
    - uses: actions/checkout@v3
    - name: fetch and extract mruby
      run: wget -O- $MRUBY_URL | tar xzf -
    - name: build
      run: |
        rake -vE 'Dir.chdir "${{env.MRUBY_DIR}}"' clean
        rake -vE 'Dir.chdir "${{env.MRUBY_DIR}}"' license
    - name: print LICENSE.yml
      run: cat "build/host/LICENSE.yml"
    - name: print LICENSE.txt
      run: cat "build/host/LICENSE.txt"
    - name: print LICENSE.html
      run: cat "build/host/LICENSE.html"
